CREATE TABLE IF NOT EXISTS mm_state (
  id BOOLEAN PRIMARY KEY DEFAULT TRUE,
  net_vsp BIGINT NOT NULL DEFAULT 0,
  unit_au DOUBLE PRECISION NOT NULL DEFAULT 0.0002,
  spread_rate DOUBLE PRECISION NOT NULL DEFAULT 1.0025,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO mm_state (id, net_vsp)
VALUES (TRUE, 0)
ON CONFLICT (id) DO NOTHING;

